# Copyright (c)  2025  OceanApocalypseStudios
# Permission is granted to copy, distribute and/or modify this document
# under the terms of the GNU Free Documentation License, Version 1.3
# or any later version published by the Free Software Foundation;
# with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.

# Global site Setup
site_url: https://oceanapocalypsestudios.github.io/rsml-docs/
site_name: Red Sea Markup Language

# Copyright
copyright: Copyright &copy; 2025  OceanApocalypseStudios

# Linking to repo
repo_url: https://github.com/OceanApocalypseStudios/rsml-docs/

# Theming
theme:
  name: material
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to system preference mode
  
  language: en
  features:
    # Footer
    - navigation.footer

    # Search sharing
    - search.share

    # Back to top button
    # Back to top seems to break on mobile
    # Making the page look wider than it is
    # It's weird and looks ugly so begone
    #- navigation.top

    # Linked tabs
    - content.tabs.link

    # Instant navigation
    - navigation.instant
    - navigation.instant.progress

    # Navigation expanded by default
    - navigation.expand

    # Show navigation path
    - navigation.path

    # Tooltips
    - content.tooltips

    # Navigation Tabs
    #- navigation.tabs

    # Code blocks
    - content.code.copy # for stealing code :)
    - content.code.annotate
  
  logo: img/logo.png
  favicon: img/favicon.ico
  icon:
    top: fontawesome/solid/angles-up
    repo: fontawesome/brands/github

# Material Plugins
plugins:
  - social # Embeds, basically 
  - search # Global docs searching

# Navigation
# All documentation must be included here, as otherwise,
# it won't be built!!
nav:
  - Home: index.md
  - Language:
    - RSML as a Language: language/index.md
    - Standards:
      - Getting Started: language/standards/index.md
      - Official 25: language/standards/official-25.md
      - Road-Like: language/standards/roadlike.md
  - API:
    - RSML as an API: api/index.md
    - Guides:
      - Getting Started: api/guides/index.md
      - Evaluating RSML from file: api/guides/eval-from-file-1.md
    - Usage Demos: api/demos.md 
    - C#:
      - Getting Started: api/csharp/index.md
      - Reference: api/csharp/reference.md
    - Python:
      - Getting Started: api/python/index.md
      - Reference: api/python/reference.md
    #- C++:
      #- Getting Started: api/cpp/index.md
      #- Reference: api/cpp/reference.md
  - CLI:
    - RSML as a CLI: cli/index.md
    - Commands: cli/commands.md
    - Real-world usage: cli/examples.md
  - Contributing: contributing.md
  - FAQ: faq.md

# Extras that should be built, but aren't docs
extra:
  # Material does not use native favicons.
  # Refer to 'theme' section.
  favicon: img/favicon.ico

  # Versioning
  version:
    provider: mike

  # Social links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OceanApocalypseStudios
    - icon: material/web
      link: https://oceanapocalypsestudios.github.io/

# CSS for advanced customization
extra_css:
  - stylesheets/extra.css

# Folders to watch for (outside docs)
watch:
  - includes

# Markdown extensions
markdown_extensions:
  # HTML Attributes in Markdown
  - attr_list

  # Table of contents
  - toc:
      permalink: true
      title: On this page

  # Markdown
  - pymdownx.details

  # Tabbed content
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  # Better Formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # Admonitions
  - admonition

  # abbreviations
  - abbr

  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite

  # definition lists - pretty good
  - def_list

  # snippets
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  
  # tasklists
  - pymdownx.tasklist:
      custom_checkbox: true # better checkboxes
  
  # Better Image Manipulation
  - md_in_html
  - pymdownx.blocks.caption

  # Tables
  - tables

  # Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Copyright (c)  2025  OceanApocalypseStudios
# Permission is granted to copy, distribute and/or modify this document
# under the terms of the GNU Free Documentation License, Version 1.3
# or any later version published by the Free Software Foundation;
# with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
