# Site Setup
site_url: https://oceanapocalypsestudios.github.io/rsml-docs/
site_name: Red Sea Markup Language

# Linking to repo
repo_url: https://github.com/OceanApocalypseStudios/rsml-docs/

# Theming
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to system preference mode
  
  language: en
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - navigation.path
  #- navigation.tabs # if we ever go with tabs instead of navigation menu. looks odd tho. i don't like it
  logo: img/logo.png
  favicon: img/favicon.ico
  icon:
    top: fontawesome/solid/angles-up
    repo: fontawesome/brands/github

# Material Plugins
plugins:
  - social # Embeds, basically 
  - search # Global docs searching

# Navigation
# All documentation must be included here, as otherwise,
# it won't be built!!
nav:
  - Home: index.md
  - Language:
    - RSML as a Language: language/index.md
    - Syntax: language/syntax.md
    - Customizable Behaviors: language/behaviors.md
    - Standards:
      - Getting Started: language/standards/index.md
      - Official 25: language/standards/official25.md
      - Road-Like: language/standards/roadlike.md
  - API:
    - RSML as an API: api/index.md
    - C#:
      - Getting Started: api/csharp/index.md
      - Reference: api/csharp/reference.md
      - Demos: api/csharp/demos.md
    - Python:
      - Getting Started: api/python/index.md
      - Reference: api/python/reference.md
      - Demos: api/python/demos.md
    - C++:
      - Getting Started: api/cpp/index.md
      - Reference: api/cpp/reference.md
      - Demos: api/cpp/demos.md
  - CLI:
    - RSML as a CLI: cli/index.md
    - Commands: cli/commands.md
    - Real-world usage: cli/examples.md
  - Migrate from MFRoad: migration.md
  - Contributing: contributing.md
  - FAQ: faq.md

# Extras that should be built, but aren't docs
extra:
  # Material does not use native favicons.
  # Refer to 'theme' section.
  favicon: img/favicon.ico

# CSS for advanced customization
extra_css:
  - stylesheets/extra.css

# Markdown extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
