// @ts-check

// [<] i think this code could be cleaner but then again my expertise
// [<] isn't JS so im sorry if this triggers anyone or something

import fs from 'fs';
import path from 'path';

/**
 * @param {string} fw
 */
function frameworkSortKey(fw) {
  const version = fw.slice(3); // [i] we couldn't care less about the "net" part
  const isModern = version.includes('.');

  if (isModern) {
    // [i] just a float conversion
    return { tier: 0, value: parseFloat(version) };
  }

  // [i] with framework it's not that easy sadly
  const major = version.slice(0, 1);
  const rest = version.slice(1);
  return { tier: 1, value: parseFloat(`${major}.${rest}`) };
}

/**
 * @param {string} a
 * @param {string} b
 */
function compareFrameworks(a, b) {
  const ka = frameworkSortKey(a);
  const kb = frameworkSortKey(b);

  if (ka.tier !== kb.tier)
    return ka.tier - kb.tier;

  return kb.value - ka.value;
}

function generateApiSidebar() {
  const apiDir = path.resolve(__dirname, 'docs/api');
  if (!fs.existsSync(apiDir)) return [];

  const frameworks = fs.readdirSync(apiDir, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name)
    .sort(compareFrameworks);

  return frameworks.map(fw => {
    const fwDir = path.join(apiDir, fw);
    if (!fs.existsSync(fwDir)) return null;

    const files = fs.readdirSync(fwDir)
      .filter(f => f.endsWith('.md'))
      .map(f => f.replace(/\.md$/, ''));

    const root = buildNamespaceTree(files, fw);
    const assemblyNode = findAssemblyRoot(root);

    return {
      type: 'category',
      label: formatFrameworkLabel(fw),
      collapsed: fw !== frameworks[0],
      link: assemblyNode.docId ? { type: 'doc', id: assemblyNode.docId } : undefined,
      items: childrenToItems(assemblyNode)
    };
  }).filter(Boolean);
}

/**
 * Builds a trie from dotted file paths.
 * @param {string[]} files
 * @param {string} fw
 */
function buildNamespaceTree(files, fw) {
  const root = { name: '', children: {}, docId: null };

  files.forEach(fileName => {
    const parts = fileName.split('.');
    let node = root;

    parts.forEach(part => {
      // @ts-ignore
      if (!node.children[part]) {
        // @ts-ignore
        node.children[part] = { name: part, children: {}, docId: null };
      }
      // @ts-ignore
      node = node.children[part];
    });

    // @ts-ignore
    node.docId = `api/${fw}/${fileName}`;
  });

  return root;
}

/**
 * Walks down while there's only a single child, to skip past the
 * reserved namespace prefix (OceanApocalypseStudios then RSML)
 * and land on the assembly's actual root namespace.
 * @param {{ name: string; children: {}; docId: null; }} root
 */
function findAssemblyRoot(root) {
  let node = root;
  while (Object.keys(node.children).length === 1) {
    const onlyChild = Object.keys(node.children)[0];
    // @ts-ignore
    node = node.children[onlyChild];
  }
  return node;
}

/**
 * Recursively turns a node's children into sidebar items.
 * A child with no children of its own is a a type becomes a document.
 * A child with children is a namespace becomes a category linked to namespace index page.
 * @param {{ name?: string; children: any; docId?: null; }} node
 */
// @ts-ignore
function childrenToItems(node) {
  const entries = Object.keys(node.children).sort().map(name => node.children[name]);
  const categories = entries.filter(child => Object.keys(child.children).length > 0);
  const types = entries.filter(child => Object.keys(child.children).length === 0);

  // @ts-ignore
  const categoryItems = categories.map(child => ({
    type: 'category',
    label: child.name,
    collapsed: true,
    link: child.docId ? { type: 'doc', id: child.docId } : undefined,
    items: childrenToItems(child)
  }));

  const typeItems = types.map(child => child.docId);

  return [...categoryItems, ...typeItems];
}

/**
 * @param {string} fw
 */
function formatFrameworkLabel(fw) {
  if (fw.startsWith('net')) {
    const version = fw.slice(3);

    if (version.includes('.'))
      return `.NET ${version}`;

    return `.NET Framework ${version.split('').join('.')}`;
  }

  return fw;
}

const sidebars = {
  bindingSidebar: [{ type: 'autogenerated', dirName: 'bindings' }],
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorials' }],
  languageSidebar: [{ type: 'autogenerated', dirName: 'language' }],
  nativeSidebar: [{ type: 'autogenerated', dirName: 'native' }],
  toolSidebar: [{ type: 'autogenerated', dirName: 'tools' }],
  apiSidebar: generateApiSidebar()
};

export default sidebars;
