// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  bindingSidebar: [{ type: 'autogenerated', dirName: 'bindings' }],
  guideSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  languageSidebar: [{ type: 'autogenerated', dirName: 'language' }],
  nativeSidebar: [{ type: 'autogenerated', dirName: 'native' }],
  toolSidebar: [{ type: 'autogenerated', dirName: 'tools' }],
  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
